# Generated by Django 3.2.6 on 2021-08-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_auto_20210813_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='direction',
            field=models.CharField(max_length=50, verbose_name='La dirección'),
        ),
    ]
